import type { GuestbookEntry } from './types'

export const MOCK_ENTRIES: GuestbookEntry[] = [
  {
    id: '1',
    created_at: '2026-03-08T11:20:00+08:00',
    guest_name: 'Keluarga Pak Long Hamid',
    relationship: 'Keluarga',
    doa: 'Barakallahu lakuma wa baraka alaikuma wa jama’a bainakuma fi khair. Semoga Anis & Aiziey kekal bahagia hingga ke Jannah. Pak Long sekeluarga sentiasa mendoakan!',
    photo_url: '/sample/guest-1.png',
    status: 'approved',
  },
  {
    id: '2',
    created_at: '2026-03-08T11:42:00+08:00',
    guest_name: 'Nurul Huda',
    relationship: 'Sahabat',
    doa: 'Anis!! Akhirnya hari yang ditunggu-tunggu tiba 🥹 Selamat pengantin baru bestie, semoga rumah tangga sentiasa dilimpahi rahmat dan kasih sayang.',
    photo_url: '/sample/guest-3.png',
    status: 'approved',
  },
  {
    id: '3',
    created_at: '2026-03-08T12:05:00+08:00',
    guest_name: 'Encik Faizal & Team IT',
    relationship: 'Rakan Kerja',
    doa: 'Tahniah Aiziey! Semoga menjadi suami yang soleh dan pemimpin keluarga yang baik. Jangan lupa cuti honeymoon cukup-cukup, kerja kami cover 😄',
    photo_url: null,
    status: 'approved',
  },
  {
    id: '4',
    created_at: '2026-03-08T12:18:00+08:00',
    guest_name: 'Mak Su Rohani',
    relationship: 'Keluarga',
    doa: 'Pelamin cantik sangat, secantik pengantinnya. Semoga dikurniakan zuriat yang soleh dan solehah. Amin ya rabbal alamin.',
    photo_url: '/sample/guest-2.png',
    status: 'approved',
  },
  {
    id: '5',
    created_at: '2026-03-08T12:30:00+08:00',
    guest_name: 'Haziq Rahman',
    relationship: 'Rakan',
    doa: 'Selamat pengantin baru bro! Sakinah, mawaddah wa rahmah. Makanan sedap gila, terbaik!',
    photo_url: null,
    status: 'approved',
  },
  {
    id: '6',
    created_at: '2026-03-08T12:51:00+08:00',
    guest_name: 'Aina Sofea',
    relationship: 'Lain-lain',
    doa: 'Walaupun baru kenal hari ini, majlis ni sangat meriah dan penuh kasih sayang. Semoga bahagia selamanya, Anis & Aiziey!',
    photo_url: '/sample/guest-4.png',
    status: 'approved',
  },
  {
    id: '7',
    created_at: '2026-03-08T13:10:00+08:00',
    guest_name: 'Syafiqah & Amir',
    relationship: 'Sahabat',
    doa: 'Dari zaman universiti sampai ke pelamin. Bangga tengok korang berdua. Semoga Allah permudahkan segala urusan dan kekal hingga syurga.',
    photo_url: null,
    status: 'approved',
  },
  {
    id: '8',
    created_at: '2026-03-08T13:15:00+08:00',
    guest_name: 'Tetamu Belum Disahkan',
    relationship: 'Rakan',
    doa: 'Contoh rekod pending — tidak sepatutnya dipaparkan di Live Gallery.',
    photo_url: null,
    status: 'pending',
  },
]
